<?php
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

$GLOBALS['sum'] = 0;
fib(1,2, 4000000);
var_dump($GLOBALS['sum']);


function fib($f1,$f2, $cap)
{
	$GLOBALS['sum'] = $f2%2==0 ? $GLOBALS['sum']+$f2 : $GLOBALS['sum'];

	$f3 = $f1+$f2;

	if ($f3 > $cap) {
		return $f1+$f2;
	}

	return $f1 + fib($f2,$f3, $cap);
}
